spring:
  application:
    name: agencyadmin
  docker:
    compose:
      enabled: false
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:createschedule}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:00000000}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

    # Kafka bootstrap server (where Kafka is running)
#spring.kafka.bootstrap-servers=localhost:9092

# Consumer group id (each service can have its own group)
#spring.kafka.consumer.group-id=location-service-group

# Key & value deserialization
#spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
